### ISSUE TITLE
Buttons don't fit in window in smallest window size of main window in source manager

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#21]
As seen in the image below the bottom buttons just don't fit in on the minimum window size.

![image](https://github.com/Lost-Empire-Entertainment/Elypso-engine/assets/59418915/e46ddfee-4348-4474-89a5-7e80f633b85b)

**Comment by greeenlaser** [comment]
im considering locking all ui movement for the imgui windows for the source manager like i did with the main window size locking

**Comment by greeenlaser** [comment]
closed because source manager was scrapped
