### ISSUE TITLE
mouse disappears when engine window is not selected when going with the mouse over the window

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#22]
When you deselect the window with the engine and try to hover over the engine window you don't see your mouse, maybe its behind the window? 

In the source manager this is not the case though.

This is a bit annoying when using more then 1 monitor and you have the app on you other monitor selected and you want to go back to the engine on your other monitor.

**Comment by greeenlaser** [comment]
seems to already be fixed in an older commit
