### ISSUE TITLE
Have a icon for the engine exe, window title and taskbar

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#24]
Think a enhancement that should be there before the release of the first beta release.

Articles that may have the solution.

https://cplusplus.com/forum/beginner/138673/
https://stackoverflow.com/questions/2393863/set-an-exe-icon-for-my-program
https://stackoverflow.com/questions/1014101/how-to-explicitly-set-taskbar-icon

**Comment by jonesy-b-dev** [comment]
Not high priority though.

**Comment by greeenlaser** [comment]
something i tried to set up pretty early in development but didnt bother after i couldnt figure it out for quite a while, ill get it set up when alpha releases in march
