### ISSUE TITLE
Allow dragging all number input fields left and right with middle mouse click to increase or decrease their values faster

### ISSUE THREAD

**Issue by greeenlaser** [Lost-Empire-Entertainment/Elypso-engine#27]
https://github.com/Lost-Empire-Entertainment/Elypso-engine/blob/eb1a2983bfb929d7c3e3c42f3d10178de443615a/Engine/src/engine/graphics/gui/gui_inspector.cpp#L105

**Comment by jonesy-b-dev** [comment]
This can be achieved using the `ImGui::DragFloat()` function
example:
```c
               // Label             v*        speed  min      max
ImGui::DragFloat("Near Clip plane", nearClip, 0.01f, 0.0001f, 1000000000);
```
