### ISSUE TITLE
When looking completely down, camera gets to wrong orientation

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#29]
When looking straight down the camera will be at a fixed angle and flipped, cant really move cam anymore. Until rotaed more and then it will change orientation. Added a gif to showcase it.

![Recording 2024-02-05 145945](https://github.com/Lost-Empire-Entertainment/Elypso-engine/assets/59418915/31d1387c-96e1-47b7-8ca4-af287d18f812)

**Comment by greeenlaser** [comment]
ok i think thats an easy thing to fix
