### ISSUE TITLE
Log input detection only on update

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#7]
Currently when `Enable input messages` is on and left mouse click is pressed, it prints the mouse values every frame.

This fills up the console really quickly and gives less overview.

Solution could be to only log when a update on the button occurs. 
Can achieve that by storing the values it gets and checking on the next frame if the values are still the same and skip logging when values are the same.

**Comment by greeenlaser** [comment]
can modify this line to reduce console spam, also add private static inline vec2 variable to input.hpp

https://github.com/Lost-Empire-Entertainment/Elypso-engine/blob/8cf1cee9159cb33b637bc7b902000f360a7bd444/src/engine/core/input.cpp#L100

**Comment by jonesy-b-dev** [comment]
Just remembered I faced this issue to when making a wireframe toggle keybind for my engine. just adding ` == GLFW_PRESS` didn't work yet. I had to put an extra check with a variable.
This is that code, setting the `m_wireframeKeyPressed` variable was the solution.
```c
void InputHandler::processInput()
{
    if (glfwGetKey(m_window, GLFW_KEY_P) == GLFW_PRESS)
    {
        if (!m_wireframeKeyPressed)
        {
            m_wireframeKeyPressed = true;

            // Toggle wireframe mode
            m_wireframeMode = !m_wireframeMode;

            // Set polygon mode based on wireframeMode
            if (m_wireframeMode)
            {
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
            }
            else
            {
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
            }
        }
    }
    else
    {
        m_wireframeKeyPressed = false;
    }
    if (glfwGetKey(m_window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
    {
        glfwSetWindowShouldClose(m_window, true);
    }
}
```

**Comment by greeenlaser** [comment]
> Just remembered I faced this issue to when making a wireframe toggle keybind for my engine. just adding ` == GLFW_PRESS` didn't work yet. I had to put an extra check with a variable. This is that code, setting the `m_wireframeKeyPressed` variable was the solution.
> 
> ```c
> void InputHandler::processInput()
> {
>     if (glfwGetKey(m_window, GLFW_KEY_P) == GLFW_PRESS)
>     {
>         if (!m_wireframeKeyPressed)
>         {
>             m_wireframeKeyPressed = true;
> 
>             // Toggle wireframe mode
>             m_wireframeMode = !m_wireframeMode;
> 
>             // Set polygon mode based on wireframeMode
>             if (m_wireframeMode)
>             {
>                 glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
>             }
>             else
>             {
>                 glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
>             }
>         }
>     }
>     else
>     {
>         m_wireframeKeyPressed = false;
>     }
>     if (glfwGetKey(m_window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
>     {
>         glfwSetWindowShouldClose(m_window, true);
>     }
> }
> ```

yes thats something i actually wanted to do as well
