### ISSUE TITLE
Engine does not build when repo is not cloned on `C:\Documents\*`

### ISSUE THREAD

**Issue by jonesy-b-dev** [Lost-Empire-Entertainment/Elypso-engine#8]
Not tested yet if it also does not work when on other directories on the C; drive.

But currently when trying to install the engine on another drive it fails the `Generate build files` option in the `RUN_ME.bat`.

**Comment by greeenlaser** [comment]
solution: either stop engine from continuing if path to engine_log.txt is invalid or skip the engine log related content and add an error message to console that engine log was not sucessfully made

**Comment by greeenlaser** [comment]
> solution: either stop engine from continuing if path to engine_log.txt is invalid or skip the engine log related content and add an error message to console that engine log was not sucessfully made

this suggestion was dumb and apparently this issue has been LONG fixed because i just compiled in D drive and opened the source in visual studio too and the project ran fine without any issues 😅😅😅

**Comment by jonesy-b-dev** [comment]
Ayyy nice
